### ISSUE TITLE
Ability to get name servers assigned by nsone in an output.

### ISSUE THREAD

**Issue by bobtfish** [bobtfish/terraform-provider-nsone#23]
We should be able to get this back from the API, and output it in a terraform output, so that this info can be displayed to users and/or used elsewhere.

Due to Terraform's terrible handling of structured data, this will probably need to be a comma separated list.

**Comment by sarguru** [comment]
This will be an attribute exported for nsone_zone resource?

**Comment by bobtfish** [comment]
Yep!
