### ISSUE TITLE
Support New Terraform API Version 2 and Terraform 0.7

### ISSUE THREAD

**Issue by spkane** [bobtfish/terraform-provider-nsone#27]
When I try to run this, using `Terraform v0.6.16` I get the following error message about the API version. 

Is there a work around or branch that resolves this problem?

```
$ terraform plan
Error configuring: 1 error(s) occurred:

* Incompatible API version with plugin. Plugin version: 1, Ours: 2
```

**Comment by spkane** [comment]
And general support for 0.7 since it has now officially shipped.

**Comment by bobtfish** [comment]
Ack, we'll be working on this ASAP

**Comment by spkane** [comment]
Thank you for the update.

**Comment by bobtfish** [comment]
This builds against 0.7 just fine. Updating the API is on the list, but not super-urgently (we're doing our 0.7 testing now)
